#!/usr/bin/env bash
#shellcheck disable=2154

[[ ! "$OSTYPE" == 'linux' ]] && return


winGpgPath="/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"

if [[ -f "$winGpgPath" ]]; then
  symlink "$topic/gitconfig_wsl" "$HOME/.gitconfig"
else
  symlink "$topic/gitconfig"
fi
