#!/usr/bin/env bash
#shellcheck disable=2154

# This is a bit of a shim to enable using Yubikey usage with GPG in WSL
# There are some fancy ways you can do it with npiperelay, but this seems to do the trick...
# I'm not a cowboy, honest...
[[ ! "$OSTYPE" == 'linux' ]] && return

if grep -q Microsoft /proc/version; then

  winGpgPath="/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"
  linuxGpgPath_user="/usr/local/bin/gpg-win"
  
  if [[ -f "$winGpgPath" ]]; then
    symlink "$winGpgPath" "$linuxGpgPath_user"
  fi
fi
