#!/usr/bin/env bash
#shellcheck disable=2154

# This is a bit of a shim to enable using Yubikey usage with GPG in WSL
# There are some fancy ways you can do it with npiperelay, but this seems to do the trick...
# I'm not a cowboy, honest...
[[ ! "$OSTYPE" == 'linux' ]] && return

winGpgPath="/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"
linuxGpgPath_user="/usr/local/bin/gpg"
linuxGpgPath="/usr/bin/gpg"
linuxGpgPathOld="/usr/bin/gpg.orig"

if [[ -f "$winGpgPath" ]]; then
  symlink "$winGpgPath" "$linuxGpgPath_user"
  # If needed, move the linux GPG binary so that it doesn't interfere with the windows one
  if [[ -f "$linuxGpgPath" ]]; then
    sudo mv "$linuxGpgPath" "$linuxGpgPathOld"
    success "$(printf "Moved %b%s%b to %b%s%b" $green "$linuxGpgPath" $reset_color $green "$linuxGpgPathOld" $reset_color )"
  fi
fi