#!/usr/bin/env bash
#shellcheck disable=2154

[[ ! "$OSTYPE" == 'linux' ]] && return

if grep -q Microsoft /proc/version; then

  #Ensure weasel-pageant is installed to interact with gpg-agent
  weaselPath="/mnt/c/bin/weasel-pageant/"
  weaselBin="weasel-pageant"

  if [[ ! -f "/mnt/c/bin/weasel-pageant/weasel-pageant" ]]; then
    cp -r $topic/weasel-pageant "/mnt/c/bin/"
    success "$(printf "Copied %b%s%b to %b%s%b" $green "weasel-pageant" $reset_color $green "/mnt/c/bin/weasel-pageant" $reset_color)"
  else
    success "$(printf "Skipped %b%s%b == %b%s%b" $green "weasel-pageant" $reset_color $green "/mnt/c/bin/weasel-pageant" $reset_color)"
  fi

  # This is a bit of a shim to enable using Yubikey usage with GPG in WSL
  # There are some fancy ways you can do it with npiperelay, but this seems to do the trick...
  # I'm not a cowboy, honest...
  # TODO: Install GPG into windows if it isnt installed? Ill need to do some reading
  winGpgPath="/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"
  linuxGpgPath_user="/usr/local/bin/gpg-win"

  if [[ -f "$winGpgPath" ]]; then
    symlink "$winGpgPath" "$linuxGpgPath_user"
  fi
fi
