#!/usr/bin/env bash
#shellcheck disable=2154

[[ ! "$OSTYPE" == 'linux' ]] && return

if grep -q Microsoft /proc/version; then

  #Ensure weasel-pageant is installed to interact with gpg-agent
  if [[ ! -f "/mnt/c/bin/weasel-pageant/weasel-pageant" ]]; then
    cp -r $topic/weasel-pageant "/mnt/c/bin/"
    success "$(printf "Copied %b%s%b to %b%s%b" $green "weasel-pageant" $reset_color $green "/mnt/c/bin/weasel-pageant" $reset_color)"
  else
    success "$(printf "Skipped %b%s%b == %b%s%b" $green "weasel-pageant" $reset_color $green "/mnt/c/bin/weasel-pageant" $reset_color)"
  fi

  #similar, but for wsl-ssh-pageant so I can use native win32 SSH with yubi SSH
  if [[ ! -f "/mnt/c/bin/wsl-ssh-pageant/wsl-ssh-pageant.exe" ]]; then
    cp -r $topic/wsl-ssh-pageant "/mnt/c/bin/"
    success "$(printf "Copied %b%s%b to %b%s%b" $green "wsl-ssh-pageant" $reset_color $green "/mnt/c/bin/wsl-ssh-pageant" $reset_color)"
  else
    success "$(printf "Skipped %b%s%b == %b%s%b" $green "wsl-ssh-pageant" $reset_color $green "/mnt/c/bin/wsl-ssh-pageant" $reset_color)"
  fi

  # This is a bit of a shim to enable using Yubikey usage with GPG in WSL
  # There are some fancy ways you can do it with npiperelay, but this seems to do the trick...
  # I'm not a cowboy, honest...
  # TODO: Install GPG into windows if it isnt installed? Ill need to do some reading
  winGpgPath="/mnt/c/Program Files (x86)/GnuPG/bin/gpg.exe"
  linuxGpgPath_user="/usr/local/bin/gpg-win"

  if [[ -f "$winGpgPath" ]]; then
    symlink "$winGpgPath" "$linuxGpgPath_user"
  fi

  # Need to set some environment variables in windows too so I can use Yubi SSH Auth under windows
  info "Setting SSH_AUTH_SOCK envirionment variable"
  /mnt/c/Windows/System32/setx.exe SSH_AUTH_SOCK '\\.\pipe\ssh-pageant'
  info "Setting GIT_SSH envirionment variable"
  /mnt/c/Windows/System32/setx.exe GIT_SSH 'C:\Windows\System32\OpenSSH\ssh.exe'

fi
