export TERM="xterm-256color"

# Check for prezto install, if not, source it
[ -d "${ZDOTDIR:-$HOME}/.zprezto" ] || git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


